services:
  backend:
    build: https://github.com/GreatGreven/rock-paper-scissor-api.git#main
    ports:
      - 8080:8080
    volumes:
      - rock-paper-scissor-api

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
